@startuml
left to right direction
skinparam packageStyle rectangle

actor Cliente
actor Empresa
actor Entregador
actor Admin

rectangle "Sistema de Delivery" {
  usecase "Cadastrar/Login" as UC01
  usecase "Visualizar produtos" as UC02
  usecase "Criar pedido" as UC03
  usecase "Calcular taxa de entrega" as UC04
  usecase "Acompanhar pedido" as UC05
  usecase "Gerenciar produtos" as UC06
  usecase "Visualizar pedidos recebidos" as UC07
  usecase "Atualizar status do pedido" as UC08
  usecase "Ficar disponível" as UC09
  usecase "Aceitar entrega" as UC10
  usecase "Finalizar entrega" as UC11
  usecase "Gerenciar usuários" as UC12
}

Cliente --> UC01
Cliente --> UC02
Cliente --> UC03
Cliente --> UC05
UC03 .> UC04 : <<include>>

Empresa --> UC01
Empresa --> UC06
Empresa --> UC07
Empresa --> UC08

Entregador --> UC01
Entregador --> UC09
Entregador --> UC10
Entregador --> UC11
Entregador --> UC08

Admin --> UC12
@enduml
